import { AdaptiveBrand, AdaptiveProduct } from '@/types'

export const singaporeBrands: AdaptiveBrand[] = [
  {
    id: 'will-and-well',
    name: 'Will & Well',
    country: 'Singapore',
    website: 'https://willandwell.com',
    singaporeAvailability: 'Local Singapore brand',
    shippingNotes: 'Free local delivery for minimum spend SGD 150',
    categories: ['Men', 'Women', 'Unisex', 'Accessories', 'Jewellery', 'Bags', 'Workshops', 'Bespoke Tailoring & Alterations'],
    adaptiveFocus: ['inclusive clothing', 'easy dressing', 'adaptive tailoring', 'functional fashion', 'dignity', 'independence'],
    notes: 'Singapore inclusive fashion label. Suitable for users who want local adaptive clothing, alterations, workshops, and stylish functional garments.',
  },
  {
    id: 'the-able-label',
    name: 'The Able Label',
    country: 'United Kingdom',
    website: 'https://www.theablelabel.com',
    singaporeAvailability: 'Ships to Singapore',
    shippingNotes: 'Singapore delivery ~8–9 working days; shipping from ~S$8, free from ~S$80',
    categories: ['Coats & Jackets', 'Shirts & Blouses', 'Tops & T-shirts', 'Knitwear', 'Nightwear & Loungewear', 'Underwear', 'Trousers', 'Skirts & Dresses', 'Socks & Slippers', 'Shoes', 'Wellbeing', 'Daily Living Aids'],
    adaptiveFocus: ['touch-and-close fastenings', 'pull-on clothing', 'arthritis-friendly', "Parkinson's", 'stroke', "Alzheimer's", 'assisted dressing'],
    notes: 'Good for older adults, carers, and users who need discreet adaptive designs.',
  },
  {
    id: 'june-adaptive',
    name: 'June Adaptive',
    country: 'Canada',
    website: 'https://www.juneadaptive.com',
    singaporeAvailability: 'Contact for international order',
    shippingNotes: 'Standard shipping US and Canada only. International customers must contact the company directly.',
    categories: ["Women's Adaptive Tops", "Women's Adaptive Pants & Jeans", "Women's Adaptive Dresses", "Women's Adaptive Sleepwear", "Men's Adaptive Tops", "Men's Adaptive Pants & Jeans", "Men's Adaptive Sleepwear", 'Footwear & Socks'],
    adaptiveFocus: ['open-back clothing', 'side-opening pants', 'wheelchair clothing', 'assisted dressing', 'arthritis', 'paralysis', "Parkinson's", 'multiple sclerosis'],
    notes: 'Contact brand directly for international orders to Singapore.',
  },
  {
    id: 'jam-the-label',
    name: 'JAM the Label',
    country: 'Australia',
    website: 'https://jamthelabel.com',
    singaporeAvailability: 'Singapore SGD store available',
    shippingNotes: 'Singapore currency store available; free shipping on orders over SGD 150',
    categories: ['Tops', 'Bottoms', 'Accessories', 'Essentials Collection', 'Tag-Free Tops', 'Yama Sensory Socks'],
    adaptiveFocus: ['sensory friendly', 'seated position', 'easy closures', 'prosthetic/medical device access', 'assisted dressing', 'energy conservation'],
    notes: 'Strong brand for younger/stylish adaptive fashion with direct SGD pricing for Singapore shoppers.',
  },
  {
    id: 'lotus-eldercare-leaf',
    name: 'Lotus Eldercare Adaptive Fashion (LEAF)',
    country: 'Singapore',
    website: 'https://www.lotuseldercare.com.sg/index.php/l-e-a-f',
    singaporeAvailability: 'Singapore-based initiative',
    shippingNotes: 'Not a standard ecommerce store — contact for availability',
    categories: ['Adaptive basics', 'Elderly clothing', 'Care clothing', 'Bed-bound patient clothing'],
    adaptiveFocus: ['elderly dressing', 'local climate', 'carer-friendly', 'occupational therapist input', 'bed-bound users'],
    notes: 'Local Singapore initiative. Add as a resource/initiative listing rather than a standard ecommerce brand.',
  },
]

export const singaporeProducts: AdaptiveProduct[] = [
  // ─── Will & Well ──────────────────────────────────────────────────────────
  {
    id: 'ww-midi-dress',
    brandId: 'will-and-well',
    brandName: 'Will & Well',
    name: 'Midi Sleeveless Dress with Front Zip',
    productType: 'Dress',
    gender: 'Women',
    category: 'Dresses',
    productUrl: 'https://willandwell.com',
    imageUrl: null,
    singaporeAvailability: 'Local Singapore brand',
    adaptiveFeatures: ['Front zipper from collar to hip', 'Easier dressing', 'Discreet accessibility'],
    bestFor: ['Limited arm mobility', 'Assisted dressing', 'Users who want stylish accessible dresses'],
    closureType: 'Front zip',
    entryType: 'product',
    sourceNotes: 'Known Will & Well product. Use brand homepage if exact live URL is unavailable.',
  },
  {
    id: 'ww-adaptive-collection',
    brandId: 'will-and-well',
    brandName: 'Will & Well',
    name: 'Adaptive & Inclusive Clothing Collection',
    productType: 'Collection',
    gender: 'Unisex',
    category: 'Adaptive clothing',
    productUrl: 'https://willandwell.com',
    imageUrl: null,
    singaporeAvailability: 'Local Singapore brand',
    adaptiveFeatures: ['Adaptive tailoring', 'Accessible closures', 'Functional garment adjustments'],
    bestFor: ['Wheelchair users', 'Elderly users', 'Disabled users', 'People with dressing difficulties'],
    entryType: 'category',
    sourceNotes: 'Category-level listing — do not present as a single SKU.',
  },
  {
    id: 'ww-tailoring',
    brandId: 'will-and-well',
    brandName: 'Will & Well',
    name: 'Bespoke Tailoring & Alterations',
    productType: 'Service',
    gender: 'Unisex',
    category: 'Tailoring / Alterations',
    productUrl: 'https://willandwell.com',
    imageUrl: null,
    singaporeAvailability: 'Local Singapore service',
    adaptiveFeatures: ['Personalised garment modification', 'Adaptive fit', 'Custom accessibility changes'],
    bestFor: ['Users who cannot find ready-made adaptive clothing'],
    entryType: 'service',
    sourceNotes: 'Service listing, not a product SKU.',
  },

  // ─── The Able Label ───────────────────────────────────────────────────────
  {
    id: 'tal-touch-close-tops',
    brandId: 'the-able-label',
    brandName: 'The Able Label',
    name: 'Touch & Close Tops / Shirts',
    productType: 'Tops',
    gender: 'Women / Men',
    category: 'Shirts & Tops',
    productUrl: 'https://www.theablelabel.com',
    imageUrl: null,
    singaporeAvailability: 'Ships to Singapore',
    adaptiveFeatures: ['Touch-and-close fastening', 'Easier self-dressing', 'Easier assisted dressing'],
    bestFor: ['Arthritis', 'Reduced dexterity', "Parkinson's", 'Stroke recovery'],
    closureType: 'Touch and close',
    entryType: 'category',
    sourceNotes: 'Category-level listing.',
  },
  {
    id: 'tal-pull-on-trousers',
    brandId: 'the-able-label',
    brandName: 'The Able Label',
    name: 'Pull-On Trousers',
    productType: 'Trousers',
    gender: 'Women / Men',
    category: 'Trousers',
    productUrl: 'https://www.theablelabel.com',
    imageUrl: null,
    singaporeAvailability: 'Ships to Singapore',
    adaptiveFeatures: ['Pull-on waist', 'No buttons or zips needed', 'Comfort fit'],
    bestFor: ['Elderly users', 'Arthritis', 'Reduced hand strength', 'Assisted dressing'],
    closureType: 'Pull-on',
    entryType: 'category',
    sourceNotes: 'Category-level listing.',
  },
  {
    id: 'tal-nightwear',
    brandId: 'the-able-label',
    brandName: 'The Able Label',
    name: 'Adaptive Nightwear & Loungewear',
    productType: 'Nightwear',
    gender: 'Women / Men',
    category: 'Nightwear & Loungewear',
    productUrl: 'https://www.theablelabel.com',
    imageUrl: null,
    singaporeAvailability: 'Ships to Singapore',
    adaptiveFeatures: ['Soft fabrics', 'Easy dressing cuts', 'Comfort-first design'],
    bestFor: ['Elderly users', 'Carers', 'Post-surgery', 'Care-home use'],
    entryType: 'category',
    sourceNotes: 'Category-level listing.',
  },
  {
    id: 'tal-underwear',
    brandId: 'the-able-label',
    brandName: 'The Able Label',
    name: 'Adaptive Underwear',
    productType: 'Underwear',
    gender: 'Women / Men',
    category: 'Underwear',
    productUrl: 'https://www.theablelabel.com',
    imageUrl: null,
    singaporeAvailability: 'Ships to Singapore',
    adaptiveFeatures: ['Easier changing', 'Comfort-focused design'],
    bestFor: ['Assisted dressing', 'Elderly users', 'Limited mobility'],
    entryType: 'category',
    sourceNotes: 'Category-level listing.',
  },
  {
    id: 'tal-socks-slippers',
    brandId: 'the-able-label',
    brandName: 'The Able Label',
    name: 'Adaptive Socks & Slippers',
    productType: 'Socks / Slippers',
    gender: 'Unisex',
    category: 'Footwear & Socks',
    productUrl: 'https://www.theablelabel.com',
    imageUrl: null,
    singaporeAvailability: 'Ships to Singapore',
    adaptiveFeatures: ['Easier foot access', 'Comfortable fit', 'Safer daily wear'],
    bestFor: ['Elderly users', 'Reduced mobility', 'Fall-risk users'],
    entryType: 'category',
    sourceNotes: 'Category-level listing.',
  },

  // ─── June Adaptive ────────────────────────────────────────────────────────
  {
    id: 'ja-mens-jeans',
    brandId: 'june-adaptive',
    brandName: 'June Adaptive',
    name: "Men's Easy-On Side-Opening Jeans",
    productType: 'Jeans',
    gender: 'Men',
    category: 'Pants & Jeans',
    price: '54.99',
    currency: 'CAD',
    productUrl: 'https://www.juneadaptive.com',
    imageUrl: null,
    singaporeAvailability: 'Contact for international order',
    adaptiveFeatures: ['Side opening', 'Adjustable waist', 'Easy-on design'],
    bestFor: ['Wheelchair users', 'Assisted dressing', 'Limited mobility'],
    closureType: 'Side opening / Velcro adjustable waist',
    entryType: 'product',
    sourceNotes: 'Customer favourite on June Adaptive.',
  },
  {
    id: 'ja-mens-polo',
    brandId: 'june-adaptive',
    brandName: 'June Adaptive',
    name: "Men's Adaptive Back-Opening Knit Polo Shirt",
    productType: 'Polo Shirt',
    gender: 'Men',
    category: 'Tops',
    price: '54.99',
    currency: 'CAD',
    productUrl: 'https://www.juneadaptive.com',
    imageUrl: null,
    singaporeAvailability: 'Contact for international order',
    adaptiveFeatures: ['Back opening', 'Snap closure', 'Assisted dressing'],
    bestFor: ['Carers', 'Elderly users', 'Limited arm mobility'],
    closureType: 'Back-opening snap closure',
    entryType: 'product',
    sourceNotes: 'Customer favourite on June Adaptive.',
  },
  {
    id: 'ja-womens-shirt',
    brandId: 'june-adaptive',
    brandName: 'June Adaptive',
    name: "Women's Easy-Access Open-Back Snap Closure Shirt",
    productType: 'Shirt',
    gender: 'Women',
    category: 'Tops',
    price: 'From 39.99',
    currency: 'CAD',
    productUrl: 'https://www.juneadaptive.com',
    imageUrl: null,
    singaporeAvailability: 'Contact for international order',
    adaptiveFeatures: ['Open back', 'Snap closure', 'Easy assisted dressing'],
    bestFor: ['Carers', 'Elderly users', 'Reduced shoulder / arm mobility'],
    closureType: 'Open-back snap closure',
    entryType: 'product',
    sourceNotes: 'Customer favourite on June Adaptive.',
  },
  {
    id: 'ja-womens-pants',
    brandId: 'june-adaptive',
    brandName: 'June Adaptive',
    name: "Women's Back-Overlap Assisted Dressing Adaptive Knit Pants",
    productType: 'Pants',
    gender: 'Women',
    category: 'Pants',
    price: '53.00',
    currency: 'CAD',
    productUrl: 'https://www.juneadaptive.com',
    imageUrl: null,
    singaporeAvailability: 'Contact for international order',
    adaptiveFeatures: ['Back-overlap design', 'Assisted dressing', 'Easy dressing'],
    bestFor: ['Wheelchair users', 'Carers', 'Limited mobility'],
    closureType: 'Back-overlap',
    entryType: 'product',
    sourceNotes: 'Customer favourite on June Adaptive.',
  },
  {
    id: 'ja-mens-long-polo',
    brandId: 'june-adaptive',
    brandName: 'June Adaptive',
    name: "Men's Adaptive Long Sleeve Back-Opening Polo Shirt",
    productType: 'Long Sleeve Polo',
    gender: 'Men',
    category: 'Tops',
    price: '64.99',
    currency: 'CAD',
    productUrl: 'https://www.juneadaptive.com',
    imageUrl: null,
    singaporeAvailability: 'Contact for international order',
    adaptiveFeatures: ['Long sleeve', 'Back opening', 'Snap closure'],
    bestFor: ['Assisted dressing', 'Carers', 'Elderly users'],
    closureType: 'Back-opening snap closure',
    entryType: 'product',
    sourceNotes: 'Customer favourite on June Adaptive.',
  },
  {
    id: 'ja-anti-slip-socks',
    brandId: 'june-adaptive',
    brandName: 'June Adaptive',
    name: 'Anti-Slip Socks',
    productType: 'Socks',
    gender: 'Unisex',
    category: 'Footwear & Socks',
    price: '40.00',
    currency: 'CAD',
    productUrl: 'https://www.juneadaptive.com',
    imageUrl: null,
    singaporeAvailability: 'Contact for international order',
    adaptiveFeatures: ['Anti-slip grip', 'Safer walking', 'Easy daily use'],
    bestFor: ['Elderly users', 'Fall-risk users', 'Hospital or home use'],
    entryType: 'product',
    sourceNotes: 'Customer favourite on June Adaptive.',
  },

  // ─── JAM the Label ────────────────────────────────────────────────────────
  {
    id: 'jam-cargo-pants',
    brandId: 'jam-the-label',
    brandName: 'JAM the Label',
    name: 'Side Access Cargo Pants',
    productType: 'Cargo Pants',
    gender: 'Unisex',
    category: 'Bottoms',
    price: '101.00',
    currency: 'SGD',
    productUrl: 'https://jamthelabel.com',
    imageUrl: null,
    singaporeAvailability: 'Singapore SGD store available',
    adaptiveFeatures: ['Side access', 'Seated-friendly fit', 'Easy access for prosthetics or medical devices'],
    bestFor: ['Wheelchair users', 'Seated users', 'Prosthetic users', 'People needing side access'],
    closureType: 'Side access',
    entryType: 'product',
    sourceNotes: 'Highlighted product on JAM the Label.',
  },
  {
    id: 'jam-zip-jumper',
    brandId: 'jam-the-label',
    brandName: 'JAM the Label',
    name: 'Zip Access Jumper',
    productType: 'Jumper',
    gender: 'Unisex',
    category: 'Tops',
    price: '110.00',
    currency: 'SGD',
    productUrl: 'https://jamthelabel.com',
    imageUrl: null,
    singaporeAvailability: 'Singapore SGD store available',
    adaptiveFeatures: ['Zip access', 'Easier dressing', 'Medical / prosthetic access'],
    bestFor: ['Assisted dressing', 'Energy conservation', 'Reduced mobility'],
    closureType: 'Zip access',
    entryType: 'product',
    sourceNotes: 'Highlighted product on JAM the Label.',
  },
  {
    id: 'jam-high-waist-pant',
    brandId: 'jam-the-label',
    brandName: 'JAM the Label',
    name: 'High Waisted Pant 2.0',
    productType: 'Pants',
    gender: 'Unisex / Women',
    category: 'Bottoms',
    price: '97.00',
    currency: 'SGD',
    productUrl: 'https://jamthelabel.com',
    imageUrl: null,
    singaporeAvailability: 'Singapore SGD store available',
    adaptiveFeatures: ['High waist', 'Seated comfort', 'Soft fit'],
    bestFor: ['Seated users', 'Wheelchair users', 'Sensory comfort'],
    entryType: 'product',
    sourceNotes: 'Highlighted product on JAM the Label.',
  },
  {
    id: 'jam-femme-linen',
    brandId: 'jam-the-label',
    brandName: 'JAM the Label',
    name: 'Femme Linen Shirt',
    productType: 'Linen Shirt',
    gender: 'Femme',
    category: 'Tops',
    price: 'From 83.00',
    currency: 'SGD',
    productUrl: 'https://jamthelabel.com',
    imageUrl: null,
    singaporeAvailability: 'Singapore SGD store available',
    adaptiveFeatures: ['Easy-wear shirt', 'Soft breathable fabric', 'Adaptive everyday styling'],
    bestFor: ['Sensory-friendly dressing', 'Everyday adaptive fashion'],
    entryType: 'product',
    sourceNotes: 'Highlighted product on JAM the Label.',
  },
  {
    id: 'jam-masc-linen',
    brandId: 'jam-the-label',
    brandName: 'JAM the Label',
    name: 'Masc. Linen Shirt',
    productType: 'Linen Shirt',
    gender: 'Masc',
    category: 'Tops',
    price: '92.00',
    currency: 'SGD',
    productUrl: 'https://jamthelabel.com',
    imageUrl: null,
    singaporeAvailability: 'Singapore SGD store available',
    adaptiveFeatures: ['Easy-wear shirt', 'Soft breathable fabric', 'Adaptive everyday styling'],
    bestFor: ['Sensory-friendly dressing', 'Everyday adaptive fashion'],
    entryType: 'product',
    sourceNotes: 'Highlighted product on JAM the Label.',
  },
  {
    id: 'jam-yama-socks',
    brandId: 'jam-the-label',
    brandName: 'JAM the Label',
    name: 'Yama Sensory Socks',
    productType: 'Socks',
    gender: 'Unisex',
    category: 'Accessories / Socks',
    productUrl: 'https://jamthelabel.com',
    imageUrl: null,
    singaporeAvailability: 'Singapore SGD store available',
    adaptiveFeatures: ['Sensory-friendly', 'Soft feel', 'Reduced irritation'],
    bestFor: ['Sensory sensitivity', 'Neurodivergent users', 'Daily comfort'],
    entryType: 'category',
    sourceNotes: 'Listed as a JAM category / collection.',
  },

  // ─── Lotus LEAF ───────────────────────────────────────────────────────────
  {
    id: 'leaf-adaptive-basics',
    brandId: 'lotus-eldercare-leaf',
    brandName: 'Lotus LEAF',
    name: 'Adaptive Basics for Elderly or Disabled Users',
    productType: 'Adaptive Basics',
    gender: 'Unisex',
    category: 'Elderly Clothing',
    productUrl: 'https://www.lotuseldercare.com.sg/index.php/l-e-a-f',
    imageUrl: null,
    singaporeAvailability: 'Singapore-based initiative',
    adaptiveFeatures: ['Suited to Singapore climate', 'Easier dressing', 'Functional design'],
    bestFor: ['Elderly users', 'Disabled users', 'Carers'],
    entryType: 'initiative',
    sourceNotes: 'Initiative-level listing. Contact LEAF for availability.',
  },
  {
    id: 'leaf-bed-bound',
    brandId: 'lotus-eldercare-leaf',
    brandName: 'Lotus LEAF',
    name: 'Bed-Bound Patient Clothing',
    productType: 'Care Clothing',
    gender: 'Unisex',
    category: 'Care Clothing',
    productUrl: 'https://www.lotuseldercare.com.sg/index.php/l-e-a-f',
    imageUrl: null,
    singaporeAvailability: 'Singapore-based initiative / in development',
    adaptiveFeatures: ['Easier changing in bed', 'Carer-friendly design', 'Patient comfort'],
    bestFor: ['Bed-bound patients', 'Carers', 'Home care', 'Eldercare'],
    entryType: 'initiative',
    sourceNotes: 'Planned / developing clothing direction. Contact LEAF for updates.',
  },
]
